spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    password: qwerty
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql


jwt:
  token:
    secret: soymun
    expired: 3600000
logging:
  config: logback-spring.xml